
version: '3'
services:
  web:
    build: .
    ports:
      - "1234:1234"
  # react:
  #   build: ../react-clien
  #   environment:
  #     - SOCKET_URL=ws://127.0.0.1:1234
  #     - API_URL=http://127.0.0.1:1234
  #   ports:
  #     - "3111:80"